# permissions for end users to view dsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dset-viewer-role
rules:
- apiGroups:
  - dset.example.com
  resources:
  - dsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dset.example.com
  resources:
  - dsets/status
  verbs:
  - get
