# permissions for end users to edit dsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dset-editor-role
rules:
- apiGroups:
  - dset.example.com
  resources:
  - dsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dset.example.com
  resources:
  - dsets/status
  verbs:
  - get
